name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial:
    git:
      url: https://github.com/edufolly/flutter_bluetooth_serial.git
      ref: master
  permission_handler: ^11.3.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
